spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DemoDb
    username: postgres
    password: 4412199.Gmc

  jpa:
    show-sql: true
    hibernate:
    ddl-auto: update

logging:
  level:
    org:
      springframework: debug


#server:
#port: 8081
#servlet:
#context-path: /location
